### ISSUE TITLE
Failed to load dilbert.com

### ISSUE THREAD

**Issue by JonnyTech** [smarek/Simple-Dilbert#60]
The app stopped working this week. A message shows `dilbert.com is not available. Loading failed.` although the page loads correctly in a browser.

Uninstalling and reinstalling does not fix it. The strange thing is that it loads previous strips correctly when swiping back. It is just the current day that fails, daily.

**Comment by smarek** [comment]
@JonnyTech cheers, dilbert.com is probably available, but their HTML changed, we do not use API, but parse HTML
Previous strips are loaded because they are cached, if you'd clear the app cache, it would start failing for historic strips as well

- [ ] Change validation message, to reflect on availability / content parsing error
- [ ] Update parsing code

**Comment by smarek** [comment]
Well that's strange, I've just checked, and it's working correctly today for me, could you maybe check/post logcat ?
2020-11-11 correct URL is https://assets.amuniversal.com/f25312c0fb5b01382ef9005056a9545d
and it should be in logcat, or there might be some long error/stacktrace 
let me know please @JonnyTech

**Comment by JonnyTech** [comment]
Well, this is embarassing, because now it works. Both of my phones had the problem last night and this morning. Thanks for your feedback. If it happens again and I am near a computer then I shall take a logcat and reopen this issue.

**Comment by jhcloos** [comment]
this reains an issue here;
the gh issue should remain open.

**Comment by smarek** [comment]
@jhcloos its different ossue now, see https://github.com/smarek/Simple-Dilbert/issues/62
