### ISSUE TITLE
Loading failed

### ISSUE THREAD

**Issue by JonnyTech** [smarek/Simple-Dilbert#62]
Every morning before 8am if I check the app it displays a black screen with an error message "dilbert.com is not available, loading failed". After 8am it starts working. I suspect maybe a date/time range check - I am in the UK and 8am here is midnight in LA and their dates match. Can I grab any logs from the app?

**Comment by dstango** [comment]
Same issue here (Germany), just it's 9am ;-). 
The reason seems to be that dilbert.com publishes new comic strips at 12am pacific, so that's way after a new day has started. 
The app isn't interested in time zones at all (using LocalDate) and takes the local current date to look up the most recent strip. 
Two ways to resolve seem possible: a) consider the time zone and adapting the day to request before checking with dilbert.com. b) in case of error change the day to yesterday and try again. While the first option prevents creating the error, the second option would be more flexible in case the publishing time might ever change, and also implicitly handle different terms for daylight saving times across countries. 
Current workaround: change the date manually.

**Comment by smarek** [comment]
Hey, it was different back then when I developed this app, see https://github.com/smarek/Simple-Dilbert/blob/master/src/main/java/com/mareksebera/simpledilbert/preferences/DilbertPreferences.java#L39

Comics were usually available from midnight of America/Chicago timezone. If it changed, it means there is few hours difference now.
I think the solution should be configurable, with default preset as we now observe it while dev/test, which can user change, in case the publishing time changes again. Will look into this, but not very soon, so if anybody would like to provide PR, i'd be happy to review it instead.

**Comment by dstango** [comment]
Yes, it looks like Chicago is not the right time zone any more... It's two hours later.
I could create a PR with the currently used time zone, but I've no Android development experience, so I wouldn't know about creating a new configuration option.

**Comment by smarek** [comment]
@dstango no worries, i can just statically change the current preset, and leave the option to configure this for later

However looking at the timezones, it's a bit strange, that we've moved outside of USA, with Chicago+2h, we can use Buenos Aires or Halifax

Chicago: https://www.timeanddate.com/time/map/#!cities=64
Buenos Aires: https://www.timeanddate.com/time/map/#!cities=51

Or did I misundestood, and the shift is actually -2 hours, meaning, we should move from Chicago to Los Angeles, California?

LA: https://www.timeanddate.com/time/map/#!cities=137

**Comment by dstango** [comment]
@smarek thank you. Yes, it needs to be e.g. Los Angeles - west coast. That should do the trick.

**Comment by jhcloos** [comment]
for me the failure is not limited to certain times of day.

it just always fails now.

**Comment by smarek** [comment]
> for me the failure is not limited to certain times of day.
> 
> it just always fails now.
> 

In that case please open new ticket and provide logs from adb and name/version of your device please, without these i am unable to help you in any way

**Comment by dstango** [comment]
dilbert.com seems to have been down during this week: https://www.reddit.com/r/dilbert/comments/yz7z28/dilbertcom_down/

I had also trouble loading, but even access with a web browser was not possible.

But the problem seems to be resolved now. As it was apparently a DNS problem it might take a little while until the fix of that reaches all DNS servers.
So I'd suggest to simply try again tomorrow.
